# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_url_bar = QtWidgets.QFrame(self.centralwidget)
        self.frame_url_bar.setGeometry(QtCore.QRect(20, 10, 421, 61))
        self.frame_url_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_url_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_url_bar.setObjectName("frame_url_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_url_bar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_accweather = QtWidgets.QPushButton(self.frame_url_bar)
        self.btn_accweather.setObjectName("btn_accweather")
        self.horizontalLayout_2.addWidget(self.btn_accweather)
        self.btn_weathercom = QtWidgets.QPushButton(self.frame_url_bar)
        self.btn_weathercom.setObjectName("btn_weathercom")
        self.horizontalLayout_2.addWidget(self.btn_weathercom)
        self.btn_windy = QtWidgets.QPushButton(self.frame_url_bar)
        self.btn_windy.setObjectName("btn_windy")
        self.horizontalLayout_2.addWidget(self.btn_windy)
        self.btn_openweather = QtWidgets.QPushButton(self.frame_url_bar)
        self.btn_openweather.setObjectName("btn_openweather")
        self.horizontalLayout_2.addWidget(self.btn_openweather)
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(460, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_status.setFont(font)
        self.lbl_status.setObjectName("lbl_status")
        self.web_container = QtWidgets.QWidget(self.centralwidget)
        self.web_container.setEnabled(True)
        self.web_container.setGeometry(QtCore.QRect(10, 80, 991, 731))
        self.web_container.setObjectName("web_container")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setGeometry(QtCore.QRect(750, 10, 251, 61))
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_title = QtWidgets.QLabel(self.frame_header)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout.addWidget(self.lbl_title)
        self.btn_refresh = QtWidgets.QPushButton(self.frame_header)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.btn_close = QtWidgets.QPushButton(self.frame_header)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_accweather.setText(_translate("MainWindow", "PushButton"))
        self.btn_weathercom.setText(_translate("MainWindow", "PushButton"))
        self.btn_windy.setText(_translate("MainWindow", "PushButton"))
        self.btn_openweather.setText(_translate("MainWindow", "PushButton"))
        self.lbl_status.setText(_translate("MainWindow", "✅ Sẵn sàng"))
        self.lbl_title.setText(_translate("MainWindow", "Thời Tiết"))
        self.btn_refresh.setText(_translate("MainWindow", "🔄 "))
        self.btn_close.setText(_translate("MainWindow", "❌"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
